{% set name = "torchsde" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google-research/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7680ec86eb2a53918a66cead8ca0f6b50dd2fe36acfc909b546d336d269d2177

build:
  skip: true  # [win and (py<37 or py>38)]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=40.8.0
  run:
    - python
    - blist
    - boltons >=20.2.1
    - numpy >=1.19.0
    - pytorch >=1.6.0
    - trampoline >=0.1.2
    - typing_extensions
    - scipy >=1.5.0

test:
  imports:
    - torchsde

about:
  home: https://github.com/google-research/torchsde
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'SDE solvers and stochastic adjoint sensitivity analysis in PyTorch.'
  description: |
    SDE solvers and stochastic adjoint sensitivity analysis in PyTorch.
  doc_url: https://github.com/google-research/torchsde
  dev_url: https://github.com/google-research/torchsde

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
